name: cicd

on:
  push:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v1
          - name: Setup Java
            uses: actions/setup-java@v1
            with:
              distribution: 'amazoncorretto'
              java-version: '21'
          - name: Build Project
            run: mvn clean install
          - name: Run Tests
            run: mvn test
          - name: Login to Docker Hub
            uses: docker/login-action@v1
            run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Build Docker Image
            run: docker build -t educacaovirtualdocker/transaction:1.0 .
          - name: Push Docker Image
            run: docker push educacaovirtualdocker/transaction:1.0

    deploy:
      needs: build
      runs-on: [aws-ec2]
      steps:
        - name: Pull the image from Docker Hub
          run: docker pull educacaovirtualdocker/transaction:1.0
        - name: Delete old container
          run: docker rm -f eduvirtual-transaction
        - name: Run the container
          run: docker run -d -p 8080:8080 --name eduvirtual-transaction educacaovirtualdocker/transaction:1.0