name: cicd

on:
  push:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Build Project
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t educacaovirtualdocker/transaction:1.0 .

      - name: Publish Docker Image to Docker Hub
        run: docker push educacaovirtualdocker/transaction:1.0

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull the image from Docker Hub
        run: docker pull educacaovirtualdocker/transaction:1.0

      - name: Delete old container
        run: docker rm -f eduvirtual-transaction || true

      - name: Run the container
        run: |
          set -x
          docker run -d -p 8080:8080 --name eduvirtual-transaction educacaovirtualdocker/transaction:1.0
